```{r}
install.packages("rtweet")
install.packages("tidytext")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("stringr")
install.packages("pander")
install.packages("kableExtra")
install.packages("rvest")
```
```{r}
library(rtweet)
library(tidytext)
library(dplyr)
library(ggplot2)
library(stringr)
library(pander)
library(kableExtra)
library(rvest)
```
```{r}
url <- "https://twitter.com/search?q=Electric%20Vehicle&src=typed_query"

twitter_page <- read_html(url)

tweets <- twitter_page %>%
  html_nodes(".tweet") %>%
  html_text()

tweet_data <- data.frame(text = tweets)
```

```{r}
tweet_data_clean <- tweet_data %>%
  mutate(cleaned_text = str_to_lower(text) %>%
           str_replace_all("[^[:alnum:][:space:]]", "") %>%
           str_replace_all("\\s+", " "))

desc_clean <- function(x){
  tk <- tibble(line = 1, text = x)
  tk <- tk %>% 
    unnest_tokens(word, text) %>% 
    anti_join(stop_words)
  return(tolower(str_c(tk$word, collapse = ' ')))
}

tweet_data_clean <- tweet_data_clean %>%
  rowwise() %>%
  mutate(cleaned_description = desc_clean(cleaned_text)) %>%
  ungroup()
```
```{r}
tweet_data_clean %>%
  ggplot(aes(x = cleaned_text)) +
  geom_bar() +
  theme_minimal() +
  labs(title = "Tweet Frequency",
       x = "Tweet Text",
       y = "Frequency")
```
